---
# Configuration for generating determinstic weekly periodic dataset 
data:
  
  - name: ER-HK-20w # name of the dataset
    seed: 1234
    neg_sampling:   # Configuration for negative edge sampling for test and validation sets.
      strategy: rnd # (CURRENTLY) TGB supports "hist_rnd" and "rnd" methods for negative edge sampling.
      hist_ratio: 0.5 # The ratio of negative edges to be sampled from historical data, and the rest randomly
      num_neg_edge: null # Number of sampled negative edges per positive edge; To consider all negatives, pass null
    num_nodes: &n 50 # Number of node for graph generation
    train_num_weeks: 20 # Number of weeks to replicate the determinstic pattern 
    permute_nodes: False # If True, then permute node indices randomly
    directed: False # Whether the graph should be directed or not
    verbose: False # If True, then display seven samples during the week.
    graphs: # The "Deterministic" graph patterns that appear during weekdays. For full list of graph generations by networkx, checkout this https://networkx.org/documentation/stable/reference/generators.html
      - days: [0, 1, 2, 3, 4]
        source: networkx
        pattern: erdos_renyi_graph
        params:
          n: *n
          p: 0.06
      - days: [5, 6]
        source: networkx
        pattern: powerlaw_cluster_graph
        params:
          n: *n
          m: 4
          p: 0.05

  - name: star-tree-20w
    seed: 2453
    neg_sampling:
      strategy: rnd
      num_neg_edge: null
    num_nodes: &n2 50
    train_num_weeks: 20
    permute_nodes: False
    directed: False
    verbose: True
    graphs:
      - days: [0, 1, 2, 3, 4]
        source: networkx
        pattern: full_rary_tree
        params:
          n: *n2
          r: 2
      - days: [5, 6]
        source: networkx
        pattern: star_graph
        params:
          n: *n2

  - name: cycle-path-20w
    seed: 23423
    neg_sampling:
      strategy: rnd
      num_neg_edge: null
    num_nodes: &n3 50
    train_num_weeks: 20
    permute_nodes: True 
    directed: False
    verbose: True
    graphs:
      - days: [0, 1, 2, 3, 4]
        source: networkx
        pattern: path_graph
        params:
          n: *n3
      - days: [5, 6]
        source: networkx
        pattern: cycle_graph
        params:
          n: *n3 

  - name: er-clique-20w
    seed: 5765
    neg_sampling:
      strategy: rnd
      num_neg_edge: null
    num_nodes: &n10 50
    train_num_weeks: 2
    permute_nodes: False 
    directed: False
    verbose: True
    graphs:
      - days: [0, 1, 2, 3, 4]
        source: TGB.tse.dataset.pattern
        pattern: er_motif_weekly
        params:
          n: *n10
          p: 0.01
          motif: complete_graph
          motif_param:
            n: 5
      - days: [5, 6]
        source: TGB.tse.dataset.pattern
        pattern: er_motif_weekly

####### 100 Weeks ########
  - name: ER-HK-100w
    seed: 1234
    neg_sampling:
      strategy: rnd 
      num_neg_edge: null
    num_nodes: &n4 50
    train_num_weeks: 100
    permute_nodes: False
    directed: False
    verbose: False
    graphs:
      - days: [0, 1, 2, 3, 4]
        source: networkx
        pattern: erdos_renyi_graph
        params:
          n: *n4
          p: 0.06
      - days: [5, 6]
        source: networkx
        pattern: powerlaw_cluster_graph
        params:
          n: *n4
          m: 4
          p: 0.05

  - name: star-tree-100w
    seed: 2453
    neg_sampling:
      strategy: rnd
      num_neg_edge: null
    num_nodes: &n5 50
    train_num_weeks: 100 
    permute_nodes: False
    directed: False
    verbose: True
    graphs:
      - days: [0, 1, 2, 3, 4]
        source: networkx
        pattern: full_rary_tree
        params:
          n: *n5
          r: 2
      - days: [5, 6]
        source: networkx
        pattern: star_graph
        params:
          n: *n5

  - name: cycle-path-100w
    seed: 23423
    neg_sampling:
      strategy: rnd
      num_neg_edge: null
    num_nodes: &n6 50
    train_num_weeks: 100 
    permute_nodes: True
    directed: False
    verbose: True
    graphs:
      - days: [0, 1, 2, 3, 4]
        source: networkx
        pattern: path_graph
        params:
          n: *n6
      - days: [5, 6]
        source: networkx
        pattern: cycle_graph
        params:
          n: *n6
  
  - name: er-clique-100w
    seed: 5765
    neg_sampling:
      strategy: rnd
      num_neg_edge: null
    num_nodes: &n11 50
    train_num_weeks: 100
    permute_nodes: False 
    directed: False
    verbose: True
    graphs:
      - days: [0, 1, 2, 3, 4]
        source: TGB.tse.dataset.pattern
        pattern: er_motif_weekly
        params:
          n: *n11
          p: 0.01
          motif: complete_graph
          motif_param:
            n: 5
      - days: [5, 6]
        source: TGB.tse.dataset.pattern
        pattern: er_motif_weekly

####### 2 Weeks ########
  - name: ER-HK-2w
    seed: 1234
    neg_sampling:
      strategy: rnd 
      num_neg_edge: null
    num_nodes: &n7 50
    train_num_weeks: 2
    permute_nodes: False
    directed: False
    verbose: False
    graphs:
      - days: [0, 1, 2, 3, 4]
        source: networkx
        pattern: erdos_renyi_graph
        params:
          n: *n7
          p: 0.06
      - days: [5, 6]
        source: networkx
        pattern: powerlaw_cluster_graph
        params:
          n: *n7
          m: 4
          p: 0.05

  - name: star-tree-2w
    seed: 2453
    neg_sampling:
      strategy: rnd
      num_neg_edge: null
    num_nodes: &n8 50
    train_num_weeks: 2 
    permute_nodes: False
    directed: False
    verbose: True
    graphs:
      - days: [0, 1, 2, 3, 4]
        source: networkx
        pattern: full_rary_tree
        params:
          n: *n8
          r: 2
      - days: [5, 6]
        source: networkx
        pattern: star_graph
        params:
          n: *n8

  - name: cycle-path-2w
    seed: 23423
    neg_sampling:
      strategy: rnd
      num_neg_edge: null
    num_nodes: &n9 50
    train_num_weeks: 2
    permute_nodes: True 
    directed: False
    verbose: True
    graphs:
      - days: [0, 1, 2, 3, 4]
        source: networkx
        pattern: path_graph
        params:
          n: *n9
      - days: [5, 6]
        source: networkx
        pattern: cycle_graph
        params:
          n: *n9
  
  - name: er-clique-2w
    seed: 5765
    neg_sampling:
      strategy: rnd
      num_neg_edge: null
    num_nodes: &n12 50
    train_num_weeks: 2
    permute_nodes: False 
    directed: False
    verbose: True
    graphs:
      - days: [0, 1, 2, 3, 4]
        source: TGB.tse.dataset.pattern
        pattern: er_motif_weekly
        params:
          n: *n12
          p: 0.01
          motif: complete_graph
          motif_param:
            n: 5
      - days: [5, 6]
        source: TGB.tse.dataset.pattern
        pattern: er_motif_weekly